name: netwash
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  image_picker: ^1.1.2

  # cloud_functions: ^5.1.3
  url_launcher: ^6.3.1

  # Firebase (Versi stabil yang kompatibel dengan web interop baru)
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1

  # State Management (Dipastikan menggunakan versi stabil ^2.x atau menyesuaikan pre-release)
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1

  # UI & Navigation
  go_router: ^14.2.0
  flutter_hooks: ^0.21.1

  # UI Components
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1

  pdf: ^3.10.7
  printing: ^5.11.1

  # Utilities
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  crypto: ^3.0.3

  # Validation
  email_validator: ^2.1.1
  http: ^1.6.0

  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  freezed: ^3.2.5
  json_serializable: ^6.7.0
  flutter_native_splash: ^2.4.8

flutter_native_splash:
  color: "#FFFFFF"          # warna background splash
  image: asset/splash/splash.png

  # opsional, kalau mau splash beda buat dark mode
  color_dark: "#121212"
  image_dark: asset/splash/splash.png

  android_12:
    image: asset/splash/splash.png
    color: "#FFFFFF"
    color_dark: "#121212"
    # icon_background_color: "#FFFFFF"  # kalau logo kamu punya padding sendiri

  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon/Netwash_Logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - asset/icon/
    - asset/splash/