// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgHDOAEiDkxQkbApNkTNowiGG_zyIVIVM',
    appId: '1:397480771765:web:fb84f2f41d77cfc94d3efc',
    messagingSenderId: '397480771765',
    projectId: 'netwash-id',
    authDomain: 'netwash-id.firebaseapp.com',
    storageBucket: 'netwash-id.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ_EX4SKODMS0L8MIiVr99BDliDdekamg',
    appId: '1:397480771765:android:b7911aa7c1a79b184d3efc',
    messagingSenderId: '397480771765',
    projectId: 'netwash-id',
    storageBucket: 'netwash-id.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMp3PJNC2EnzJzYDk3u_gSU5DZTADBN8k',
    appId: '1:397480771765:ios:c4d1135a8d9b8f6f4d3efc',
    messagingSenderId: '397480771765',
    projectId: 'netwash-id',
    storageBucket: 'netwash-id.firebasestorage.app',
    androidClientId: '397480771765-mjkcg7r81ot650k6dtqnuvifjhvrofqu.apps.googleusercontent.com',
    iosClientId: '397480771765-c48mulrbrb40mmoqjacnt0cm1ii74aet.apps.googleusercontent.com',
    iosBundleId: 'com.netwash.pklLaundry',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMp3PJNC2EnzJzYDk3u_gSU5DZTADBN8k',
    appId: '1:397480771765:ios:c4d1135a8d9b8f6f4d3efc',
    messagingSenderId: '397480771765',
    projectId: 'netwash-id',
    storageBucket: 'netwash-id.firebasestorage.app',
    androidClientId: '397480771765-mjkcg7r81ot650k6dtqnuvifjhvrofqu.apps.googleusercontent.com',
    iosClientId: '397480771765-c48mulrbrb40mmoqjacnt0cm1ii74aet.apps.googleusercontent.com',
    iosBundleId: 'com.netwash.pklLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgHDOAEiDkxQkbApNkTNowiGG_zyIVIVM',
    appId: '1:397480771765:web:866198d74acdc7104d3efc',
    messagingSenderId: '397480771765',
    projectId: 'netwash-id',
    authDomain: 'netwash-id.firebaseapp.com',
    storageBucket: 'netwash-id.firebasestorage.app',
  );
}
